### ISSUE TITLE
Tuya mock

### ISSUE THREAD

**Issue by briggitteorellana** [TuyaAPI/stub#3]
¿¿¿how do i emulate a device tuya?

**Comment by codetheweb** [comment]
Documentation is here: https://tuyaapi.github.io/stub/index.html

It may be helpful to look at the tests for TuyAPI, which use the stub module: https://github.com/codetheweb/tuyapi/blob/master/test/stub.js.

**Comment by briggitteorellana** [comment]
thanks, but how do i run this file, how do i use it? sorry but i'm new to this and i need to use. thank youuuu
![como](https://user-images.githubusercontent.com/51811237/94074325-ab6ecb80-fdbe-11ea-869b-3ef0a94f9a02.JPG)

**Comment by briggitteorellana** [comment]
![enviar](https://user-images.githubusercontent.com/51811237/94086588-06a9b980-fdd1-11ea-9208-86e984b48d68.JPG)


I don't know if I'm fine, I don't know what else to do to run , help please

**Comment by codetheweb** [comment]
I'm not really sure what you're trying to accomplish.

It looks like your questions have to do with the basics of Javascript / Node.js rather than TuyAPI, so I'd suggest asking a more specific question somewhere like StackOverflow.

**Comment by briggitteorellana** [comment]
ava-cli is used to run it??

**Comment by briggitteorellana** [comment]
I managed to run it, excuse me how can I manage the device on and off?? 
![enviiii](https://user-images.githubusercontent.com/51811237/94385582-214e9c00-010b-11eb-8c67-cdd8b5b48ca9.JPG)

**Comment by codetheweb** [comment]
According to the documentation, you can use `setState()` on a stub instance: https://tuyaapi.github.io/stub/index.html#tuyastubsetstate.

**Comment by briggitteorellana** [comment]
is this project used to simulate a virtual device?

**Comment by codetheweb** [comment]
Yes.
